doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(DEFAULT_DATABASE_URL)%'
            authme:
                url: '%env(AUTHME_DATABASE_URL)%'
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: true
        entity_managers:
            default:
                connection: default
                mappings:
                    Main:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Main'
                        prefix: 'App\Entity\Main'
                        alias: Main
            authme:
                connection: authme
                mappings:
                    Customer:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Authme'
                        prefix: 'App\Entity\Authme'
                        alias: Authme