version: '3'

services:
    ###> doctrine/doctrine-bundle ###
    database:
        image: 'mysql:latest'
        environment:
            MYSQL_ROOT_PASSWORD: 1111
            MYSQL_DATABASE: cloudy
        ports:
            - "3306:3306"
        volumes:
            - "db-data:/var/lib/mysql"
#    fpm:
#        build:
#            context: ./fpm
#        volumes:
#            - ../:/var/www/symfony:cached
#            - ./fpm/xdebug.ini:/etc/php/conf.d/xdebug.ini
#    nginx:
#        image: 'nginx:latest'
#        volumes:
#            - /home/ihor/PhpstormProjects/Minecraft-Cloudy/nginx.conf:/etc/nginx/conf.d/default.conf
#            - ../:/var/www/symfony
#        depends_on:
#            - fpm
#        ports:
#            - "8080:80"
#        links:
#            - fpm


volumes:
    db-data: